CREATE TABLE IF NOT EXISTS MATHS_BIO (
    URL TEXT,
    WHOLE_TEXT TEXT,
    TITLE TEXT,
    SHORT_DESCRIPTION TEXT,
    H1 TEXT,
    NAME TEXT,
    BIRTH_LOCATION TEXT,
    BIRTH_DATE DATE,
    DEATH_LOCATION TEXT,
    DEATH_DATE DATE
) TABLESPACE mydbspace;